#!/bin/sh
alias ｌｓ="ls"
alias ｓｌ="sl"
alias ｃｄ="cd"
alias ｃｐ="cp"
alias ｍｖ="mv"
alias ｒｍ="rm"
alias じｐ="zip"
alias うんじｐ="unzip"
alias れなめ="rename"
alias ｐｙてょん３="python3"
alias ばｓｈ="bash"
alias ｚｓｈ="zsh"
alias っｄ="dd"
alias ｈとｐ="htop"
alias ゔぃｍ="vim"
alias なの="nano"
alias あｐｔ="apt"
alias ｓなｐ="snap"
alias っｓｈ="ssh"
alias くｒｌ="curl"
alias ｗげｔ="wget"
alias ｓｈ="sh"
alias まｎ="man"
alias こで="code"
alias えちょ="echo"
alias ｃｈもｄ="chmod"

alias あｄｂ="adb"
alias ふぁｓｔぼおｔ="fastboot"
alias っｆｍぺｇ="ffmpeg"
alias ｇせっちんｇｓ="gsettings"

alias ぁ="ls -a"
alias っｌ="ls -l"
